//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.02 at 04:13:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:x-gsip:1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nrcan.lms.gsc.gsip.conf;
